## Coleta de dados estruturados em lista de arquivos

Um instituto de pesquisa realizou no ano de 2020 uma pesquisa que tinha como objetivo coletar
dados sobre as preferências pessoais de seus entrevistados. Essa pesquisa coletou dados dos
seguintes assuntos:
1. Animal de estimação.
2. Bebida.
3. Clima.
4. Hobbies.

A pesquisa foi realizada em dias diferentes durante todo o ano de 2020. Dessa forma,
cada dia da pesquisa contém informações pessoais de um ou vários entrevistados

In [ ]:
#Vamos importar as bibliotecas que vamos utilizar para essa prática
import pandas as pd 
import os # bibliotecas para funções do sistema operacional

### Documentação das bibliotecas
**Pandas** - https://pandas.pydata.org/pandas-docs/stable/index.html

**os** - https://docs.python.org/3/library/os.html

Vamos atribuir a uma váriavel o caminho no qual está armazenados os arquivos com as vendas do veículo

In [ ]:
DIRETORIO = "/content/files/"

Agora vamos criar uma lista com todos os arquivos que estão armazenados no diretório.

o metódo listdir retorna uma lista contendo os nomes das entradas no diretório fornecido por path.

In [ ]:
lista_df = [] # cria uma lista
lista_path = os.listdir(DIRETORIO)

In [ ]:
lista_path[:3] #lista quantidade de itens na lista

['2020-01-16.csv', '2020-12-19.csv', '2020-01-13.csv']

Ótmo! Agora temos todos os nomes dos aquivos que estão dentro do diretório. Agora vamos abrir cada arquivo e coletar os seus dados.

In [ ]:
lista_df = [] # cria uma lista vazia
for arquivo in lista_path:
    local_arquivo = os.path.join(DIRETORIO, arquivo)
    df = pd.read_csv(local_arquivo, sep = '|', encoding='latin-1')
    lista_df.append(df)
df_pesquisa = pd.concat(lista_df) # Atribui os dados coletados em um dataframe

In [ ]:
lista_new = [] # cria uma lista vazia
for arquivo in lista_path:
    if arquivo != '.ipynb_checkpoints':
      local_arquivo = os.path.join(DIRETORIO, arquivo)
      dfnew = pd.read_csv(local_arquivo, sep = '|', encoding='latin-1')
      lista_new.append(dfnew)
#df_pesquisa = pd.concat(lista_df) # Atribui os dados coletados em um dataframe
df_new= pd.concat(lista_new) # Atribui os dados coletados em um dataframe

In [ ]:
#df_pesquisa[:10]
df_new.head()

,cod_pessoa,data_coleta,genero,data_nascimento,animal_estimacao,clima,bebida_favorita,hobbies
0,10142036,2020-01-16,Feminino,1965-04-19,tartaruga,frio,Água,Escutar música
1,10142053,2020-01-16,Feminino,1968-10-21,peixe,quente,refrigerante,Praticar esporte
0,10141876,2020-12-19,Feminino,1972-12-20,gato,frio,Vinho,Aprender algo novo
1,10141899,2020-12-19,Masculino,1969-09-18,gato,moderado,Chá,Pintar quadros
2,10143110,2020-12-19,Masculino,1951-07-25,gato,moderado,refrigerante,Praticar esporte

In [ ]:
df_pesquisa.describe()

         cod_pessoa
count  2.127000e+03
mean   1.014256e+07
std    6.141563e+02
min    1.014150e+07
25%    1.014203e+07
50%    1.014256e+07
75%    1.014310e+07
max    1.014363e+07

In [ ]:
df_pesquisa.head()

,cod_pessoa,data_coleta,genero,data_nascimento,animal_estimacao,clima,bebida_favorita,hobbies
0,10142036,2020-01-16,Feminino,1965-04-19,tartaruga,frio,Água,Escutar música
1,10142053,2020-01-16,Feminino,1968-10-21,peixe,quente,refrigerante,Praticar esporte
0,10141876,2020-12-19,Feminino,1972-12-20,gato,frio,Vinho,Aprender algo novo
1,10141899,2020-12-19,Masculino,1969-09-18,gato,moderado,Chá,Pintar quadros
2,10143110,2020-12-19,Masculino,1951-07-25,gato,moderado,refrigerante,Praticar esporte

# Exportando dados para arquivos

Agora que ja temos todos os arquivos do diretório, vamos exporta-los apenas para um arquivo único.

In [ ]:
df_pesquisa.to_csv(DIRETORIO + '/pesquisa_completa.csv', sep = ';', encoding='latin-1', index=False)

Agora temos os dados das vendas em um único arquivo. Abaixo segue a prévia do arquivo exportado.

#Questões do Desafio

Carregando biblioteca de SQL do pandas

In [ ]:
!pip install -U pandasql #Lib pandas SQL

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandasql in /usr/local/lib/python3.7/dist-packages (0.7.3)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.7/dist-packages (from pandasql) (1.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from pandasql) (1.3.5)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from pandasql) (1.21.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->pandasql) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->pandasql) (2022.2.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->pandasql) (1.15.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.7/dist-packages (from sqlalchemy->pandasql) (1.1.3)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from sqlalchemy->pandasql) (4.12.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->sqlalchemy->pandasql) (4.1.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->sqlalchemy->pandasql) (3.8.1)

In [ ]:
from pandasql import sqldf
from sklearn import datasets

In [ ]:
# Teste de Query SQL
q = "SELECT * FROM df_pesquisa LIMIT 20"
sqldf(q, globals())

,cod_pessoa,data_coleta,genero,data_nascimento,animal_estimacao,clima,bebida_favorita,hobbies
0,10142036,2020-01-16,Feminino,1965-04-19,tartaruga,frio,Água,Escutar música
1,10142053,2020-01-16,Feminino,1968-10-21,peixe,quente,refrigerante,Praticar esporte
2,10141876,2020-12-19,Feminino,1972-12-20,gato,frio,Vinho,Aprender algo novo
3,10141899,2020-12-19,Masculino,1969-09-18,gato,moderado,Chá,Pintar quadros
4,10143110,2020-12-19,Masculino,1951-07-25,gato,moderado,refrigerante,Praticar esporte
5,10143158,2020-12-19,Feminino,1988-10-18,gato,quente,refrigerante,Escutar música
6,10143159,2020-12-19,Feminino,1956-07-16,peixe,quente,Café,Escutar música
7,10141518,2020-01-13,Masculino,1959-06-12,tartaruga,frio,Água,Aprender algo novo
8,10142083,2020-01-13,Masculino,1959-02-22,gato,moderado,Água,Dormir
9,10142537,2020-01-13,Masculino,1994-08-20,cachorro,quente,Cerveja,Escrever
10,10142628,2020-01-13,Feminino,1954-04-20,gato,moderado,Vinho,Aprender algo novo
11,10142815,2020-01-13,Masculino,1962-03-21,cachorro,quente,Café,Dormir
12,10142923,2020-01-13,Masculino,1980-10-28,cachorro,quente,Chá,Assistir TV
13,10142148,2020-08-14,Feminino,1975-04-02,cachorro,moderado,Água,Aprender algo novo
14,10142539,2020-08-14,Masculino,1962-09-07,gato,frio,Cerveja,Escrever
15,10142847,2020-08-14,Masculino,1957-10-25,tartaruga,frio,Cerveja,Pintar quadros
16,10141597,2020-09-24,Feminino,1985-03-09,peixe,moderado,Chá,Escrever
17,10141977,2020-09-24,Feminino,1980-10-31,tartaruga,frio,refrigerante,Escutar música
18,10142499,2020-09-24,Masculino,1973-12-31,peixe,frio,refrigerante,Pintar quadros
19,10142723,2020-09-24,Masculino,1980-04-07,gato,moderado,Cerveja,Praticar esporte

## 1. Qual é a soma das Pessoas que gostam de gato ou cachorro? Utilize operador IN na clausura where.

In [ ]:
q = "SELECT COUNT(*) as TOTAL FROM df_pesquisa WHERE animal_estimacao IN ('gato', 'cachorro')"
sqldf(q, globals())

   TOTAL
0   1278

## 2. Qual a média de idade dos mulheres que gostam de chá e clima frio?

In [ ]:
q = "SELECT AVG((strftime('%Y', 'now') - strftime('%Y', data_nascimento)) - (strftime('%m-%d', 'now') < strftime('%m-%d', data_nascimento))) as media_idade FROM "
q+="df_pesquisa WHERE genero='Feminino' AND clima='frio' AND bebida_favorita='Chá'"
sqldf(q, globals())

   media_idade
0    49.890909

## 3. Qual o segundo maior hobbie de preferência entre os homens?

In [ ]:
q = "SELECT COUNT(hobbies) as hobbie, hobbies FROM df_pesquisa WHERE genero='Masculino' GROUP BY hobbies ORDER BY COUNT(hobbies) DESC;"
sqldf(q, globals())

   hobbie             hobbies
0     184              Dormir
1     183  Aprender algo novo
2     182            Escrever
3     177          Ler livros
4     175    Praticar esporte
5     173         Assistir TV
6     171      Pintar quadros
7     153      Escutar música

## 5. Qual o resultado da consulta abaixo?
select aes.animal, count(pes.cod_pessoa) as qtd_pessoas
 from pesquisa as pesq
 join animal_estimacao aes on
                 pesq.cod_animal_estimacao = aes.cod_animal_estimacao
 join pessoa as pes on
                 pesq.cod_pessoa = pes.cod_pessoa
 group by aes.animal
order by count(pes.cod_pessoa) desc

In [ ]:
#Estatística que apresenta o índice de pessoas que possuem preferência por tipo de animal e classificado de maneira decrescente.

## 6. Qual é a média de idade das pessoas que têm como hobbie assistir TV?

In [ ]:
q = "SELECT AVG((strftime('%Y', 'now') - strftime('%Y', data_nascimento)) - (strftime('%m-%d', 'now') < strftime('%m-%d', data_nascimento))) as media_idade FROM df_pesquisa WHERE hobbies='Assistir TV' ORDER BY COUNT(hobbies) DESC;"
sqldf(q, globals())

   media_idade
0    46.247148

## 7. Quantas pessoas têm como hobbie como ler livros e qual a sua média de idade respectivamente?

In [ ]:
q = "SELECT COUNT(1) as total, hobbies, AVG((strftime('%Y', 'now') - strftime('%Y', data_nascimento)) - (strftime('%m-%d', 'now') < strftime('%m-%d', data_nascimento))) as media_idade FROM df_pesquisa WHERE hobbies='Ler livros' GROUP BY hobbies ORDER BY COUNT(hobbies) DESC;"
sqldf(q, globals())

   total     hobbies  media_idade
0    257  Ler livros    45.750973

##8. Qual script abaixo retorna o número total de pessoas que responderam na pesquisa que gostam de cachorro?

In [ ]:
'''select ae.animal, count(1) total
from pesquisa p
inner join animal_estimacao ae
on p.cod_animal_estimacao = ae.cod_animal_estimacao
where ae.animal = 'cachorro'
group by animal 
'''

q = "SELECT animal_estimacao, COUNT(1) as total FROM df_pesquisa WHERE animal_estimacao='cachorro' GROUP BY animal_estimacao"
sqldf(q, globals())

  animal_estimacao  total
0         cachorro    414

## 9. Qual a quantidade de pessoas que gostam de tempo moderado?

In [ ]:
q = "SELECT COUNT(*) as TOTAL FROM df_pesquisa WHERE clima='moderado'"
sqldf(q, globals())

   TOTAL
0    711

##10. Qual o animal de estimação preferido entre as mulheres?

In [ ]:
q = "SELECT COUNT(animal_estimacao) as total, animal_estimacao FROM df_pesquisa WHERE genero='Feminino' GROUP BY animal_estimacao ORDER BY COUNT(animal_estimacao) DESC;"
sqldf(q, globals())

## 11. Quantas pessoas gostam de clima quente por gênero?

In [ ]:
q = "SELECT COUNT(clima) as total, genero FROM df_pesquisa WHERE clima='quente' GROUP BY clima, genero ORDER BY COUNT(clima) DESC;"
sqldf(q, globals())

   total     genero
0    447  Masculino
1    246   Feminino

## 12. Quantas pessoas do sexo masculino gostam de cachorro e possuem hobbie de assistir tv?

In [ ]:
q = "SELECT COUNT(*) as TOTAL FROM df_pesquisa WHERE animal_estimacao = 'cachorro' AND genero = 'Masculino' AND hobbies='Assistir TV'"
sqldf(q, globals())

   TOTAL
0     44

#  Armazendo os dados no banco dados MySQL

Vamos importar as bibliotecas necessárias para trabalhar no banco de dados

In [ ]:
!pip install mysqlclient

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: mysqlclient in /usr/local/lib/python3.7/dist-packages (2.1.1)

In [ ]:
!pip install sqlalchemy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.7/dist-packages (1.4.1)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from sqlalchemy) (4.12.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.7/dist-packages (from sqlalchemy) (1.1.3)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->sqlalchemy) (3.8.1)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->sqlalchemy) (4.1.1)

### Documentação das bibliotecas
**MySQLdb** - https://mysqlclient.readthedocs.io/user_guide.html

**sqlalchemy** - https://www.sqlalchemy.org/


### Criando schema do banco de dados
O próximo passo é criar a conexão com o banco de dados. No entanto, antes de executar o script que gera a string de conexão precisamos criar o schema no banco de dados. 

Os **schemas** são coleções de objetos dentro de um determinado banco de dados, que organizam vários aspectos e são importantes para segmentação da segurança, facilitando a administração dos objetos e dos dados. 

Para criar o o schema de um banco de dados MySQL temos que utilizar o seguinte comando dentro do ambiente do SGDB:

> create schema [nome_schema];

SGBD é o sistema gerenciador de banco de dados. Para esse curso vamos utilizar o MySQL Workbench.

Pronto! Depois que criamos o schema/database dentro do MySQL Workbenck o proximo passo é criar a conexão com o banco.
Vamos definir os dados necessárias para fazer o acesso ao servidor de banco de dados MySQL e, em seguinda, criar uma conexão com o banco de dados baseado em uma string de conexão.

In [1]:
user = 'db_odiego'
password = 'senha'
host = 'localhost'
database = 'db_odiego' #schema

string_conexao = f'mysql://{user}:{password}@{host}/{database}'
string_conexao #testar a string de conexão com o banco de dados.

'mysql://db_odiego:senha@localhost/db_odiego'

A string é composta pelo o **usuário** de acesso ao banco, a **senha**, o **caminho** do banco de dados e o **schema** que vai ser utilizado.

In [ ]:
from sqlalchemy import create_engine

engine = create_engine(string_conexao)
conn = engine.connect()

O primeiro passo é inserir os dados do dataframe **df_pesquisa** na tabela no banco. 
Para isso, vamos percorrer todo o dataframe e atribuir as variáveis os valores de cada coluna. Em seguida, vamos inseri-las no insert.

In [ ]:
for pessoa in df_pesquisa[:3].itertuples():
    print(pessoa)

Pandas(Index=0, cod_pessoa=10142036, data_coleta='2020-01-16', genero='Feminino', data_nascimento='1965-04-19', animal_estimacao='tartaruga', clima='frio', bebida_favorita='Água', hobbies='Escutar música')
Pandas(Index=1, cod_pessoa=10142053, data_coleta='2020-01-16', genero='Feminino', data_nascimento='1968-10-21', animal_estimacao='peixe', clima='quente', bebida_favorita='refrigerante', hobbies='Praticar esporte')
Pandas(Index=0, cod_pessoa=10141876, data_coleta='2020-12-19', genero='Feminino', data_nascimento='1972-12-20', animal_estimacao='gato', clima='frio', bebida_favorita='Vinho', hobbies='Aprender algo novo')

Observerm que para o animal_estimacao não foi gerado um dataframe e sim uma lista. Não foi necessário criar um dataframe, uma vez que os dados contidos são apenas de uma coluna.

In [ ]:
df_pesquisa[:20].itertuples()
df_animal = df_pesquisa['animal_estimacao']
animais = list(df_animal.unique())
animais #Dados de modelo

['tartaruga', 'peixe', 'gato', 'cachorro']

In [ ]:
for animal in animais:
  print(animal)

tartaruga
peixe
gato
cachorro

In [ ]:
for animal in animais:
    try:
        query = f"""insert into animal_estimacao (animal) 
                     values ('{animal}')"""
        conn.execute(query)
        print(f"Registro inserido com sucesso: {animal}")
    except Exception as e:
        print(f"Não foi possível inserir o regristro {animal}. O erro foi encontrado foi: {e}")

Não foi possível inserir o regristro tartaruga. O erro foi encontrado foi: (MySQLdb.OperationalError) (2013, 'Lost connection to MySQL server during query')
[SQL: insert into animal_estimacao (animal)
                     values ('tartaruga')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
Registro inserido com sucesso: peixe
Registro inserido com sucesso: gato
Registro inserido com sucesso: cachorro

## Dados de Clima, Bebidas e Hobbies

In [ ]:
df_clima = df_pesquisa['clima']
climas = list(df_clima.unique())
climas #Dados de modelo

['frio', 'quente', 'moderado']

In [ ]:
df_bebida = df_pesquisa['bebida_favorita']
bebidas = list(df_bebida.unique())
bebidas #Dados de modelo

['Água', 'refrigerante', 'Vinho', 'Chá', 'Café', 'Cerveja']

In [ ]:
df_hobbie = df_pesquisa['hobbies']
hobbies = list(df_hobbie.unique())
hobbies #Dados de modelo

['Escutar música',
 'Praticar esporte',
 'Aprender algo novo',
 'Pintar quadros',
 'Dormir',
 'Escrever',
 'Assistir TV',
 'Ler livros']

## Inserção no DB (Clima, Bebidas e Hobbies)

In [ ]:
# Lista de climas
for clima in climas:
    try:
        query = f"""insert into clima (clima) 
                     values ('{clima}')"""
        conn.execute(query)
        print(f"Registro inserido com sucesso: {clima}")
    except Exception as e:
        print(f"Não foi possível inserir o regristro {clima}. O erro foi encontrado foi: {e}")

Não foi possível inserir o regristro frio. O erro foi encontrado foi: (MySQLdb.OperationalError) (2013, 'Lost connection to MySQL server during query')
[SQL: insert into clima (clima)
                     values ('frio')]
(Background on this error at: http://sqlalche.me/e/14/e3q8)
Registro inserido com sucesso: quente
Registro inserido com sucesso: moderado

In [ ]:
# Lista de bebidas
for drink in bebidas:
    try:
        query = f"""insert into bebida (bebida) 
                     values ('{drink}')"""
        conn.execute(query)
        print(f"Registro inserido com sucesso: {drink}")
    except Exception as e:
        print(f"Não foi possível inserir o regristro {drink}. O erro foi encontrado foi: {e}")

Não foi possível inserir o regristro Água. O erro foi encontrado foi: (MySQLdb.OperationalError) (2013, 'Lost connection to MySQL server during query')
[SQL: insert into bebida (bebida)
                     values ('Água')]
(Background on this error at: http://sqlalche.me/e/14/e3q8)
Registro inserido com sucesso: refrigerante
Registro inserido com sucesso: Vinho
Registro inserido com sucesso: Chá
Registro inserido com sucesso: Café
Registro inserido com sucesso: Cerveja

In [ ]:
# Lista de hobbies
for hb in hobbies:
    try:
        query = f"""insert into hobbie (hobbie) 
                     values ('{hb}')"""
        conn.execute(query)
        print(f"Registro inserido com sucesso: {hb}")
    except Exception as e:
        print(f"Não foi possível inserir o regristro {hb}. O erro foi encontrado foi: {e}")

# Data Frame de pessoas

In [ ]:
df_pessoa = df_pesquisa[['cod_pessoa', 'genero', 'data_nascimento']].drop_duplicates()
df_pessoa

    cod_pessoa     genero data_nascimento
0     10142036   Feminino      1965-04-19
1     10142053   Feminino      1968-10-21
0     10141876   Feminino      1972-12-20
1     10141899  Masculino      1969-09-18
2     10143110  Masculino      1951-07-25
..         ...        ...             ...
1     10141591   Feminino      1970-10-13
2     10141873   Feminino      1956-10-10
3     10142141  Masculino      1958-07-12
4     10142626   Feminino      1957-11-11
5     10142979  Masculino      1952-03-25

[2127 rows x 3 columns]

In [ ]:
for pessoa in df_pessoa.itertuples():
    cod_pessoa = pessoa.cod_pessoa
    genero = pessoa.genero
    data_nascimento = str(pessoa.data_nascimento)

    try:
        query = f"""insert into pessoa (cod_pessoa, genero, data_nascimento ) 
                     values ('{cod_pessoa}','{genero}', '{data_nascimento}')"""      
        conn.execute(query)      
        print(f"Registro inserido com sucesso: {cod_pessoa}")
    except Exception as e:        
        print(f"Não foi possível inserir o regristro {cod_pessoa}. O erro foi encontrado foi: {e}")

Não foi possível inserir o regristro 10142036. O erro foi encontrado foi: (MySQLdb.OperationalError) (2013, 'Lost connection to MySQL server during query')
[SQL: insert into pessoa (cod_pessoa, genero, data_nascimento )
                     values ('10142036','Feminino', '1965-04-19')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
Registro inserido com sucesso: 10142053
Registro inserido com sucesso: 10141876
Registro inserido com sucesso: 10141899
Registro inserido com sucesso: 10143110
Registro inserido com sucesso: 10143158
Registro inserido com sucesso: 10143159
Registro inserido com sucesso: 10141518
Registro inserido com sucesso: 10142083
Registro inserido com sucesso: 10142537
Registro inserido com sucesso: 10142628
Registro inserido com sucesso: 10142815
Registro inserido com sucesso: 10142923
Registro inserido com sucesso: 10142148
Registro inserido com sucesso: 10142539
Registro inserido com sucesso: 10142847
Registro inserido com sucesso: 10141597
Registro inserido com sucesso: 10141977
Registro inserido com sucesso: 10142499
Registro inserido com sucesso: 10142723
Registro inserido com sucesso: 10142899
Registro inserido com sucesso: 10143168
Registro inserido com sucesso: 10141728
Registro inserido com sucesso: 10142960
Registro inserido com sucesso: 10143039
Registro inserido com sucesso: 10141824
Registro inserido com sucesso: 10141910
Registro inserido com sucesso: 10141955
Registro inserido com sucesso: 10142143
Registro inserido com sucesso: 10142661
Registro inserido com sucesso: 10143290
Registro inserido com sucesso: 10143451
Registro inserido com sucesso: 10142118
Registro inserido com sucesso: 10142724
Registro inserido com sucesso: 10142803
Registro inserido com sucesso: 10142834
Registro inserido com sucesso: 10143214
Registro inserido com sucesso: 10143588
Registro inserido com sucesso: 10141875
Registro inserido com sucesso: 10142372
Registro inserido com sucesso: 10143549
Registro inserido com sucesso: 10141576
Registro inserido com sucesso: 10141803
Registro inserido com sucesso: 10142010
Registro inserido com sucesso: 10142014
Registro inserido com sucesso: 10142767
Registro inserido com sucesso: 10141752
Registro inserido com sucesso: 10142208
Registro inserido com sucesso: 10142428
Registro inserido com sucesso: 10142649
Registro inserido com sucesso: 10143266
Registro inserido com sucesso: 10143271
Registro inserido com sucesso: 10143367
Registro inserido com sucesso: 10143463
Registro inserido com sucesso: 10143529
Registro inserido com sucesso: 10143627
Registro inserido com sucesso: 10141651
Registro inserido com sucesso: 10142846
Registro inserido com sucesso: 10142857
Registro inserido com sucesso: 10143505
Registro inserido com sucesso: 10141942
Registro inserido com sucesso: 10142080
Registro inserido com sucesso: 10142218
Registro inserido com sucesso: 10142782
Registro inserido com sucesso: 10142939
Registro inserido com sucesso: 10143031
Registro inserido com sucesso: 10143579
Registro inserido com sucesso: 10141763
Registro inserido com sucesso: 10142046
Registro inserido com sucesso: 10142408
Registro inserido com sucesso: 10142576
Registro inserido com sucesso: 10142819
Registro inserido com sucesso: 10143087
Registro inserido com sucesso: 10143464
Registro inserido com sucesso: 10141610
Registro inserido com sucesso: 10141776
Registro inserido com sucesso: 10141929
Registro inserido com sucesso: 10142308
Registro inserido com sucesso: 10142404
Registro inserido com sucesso: 10142483
Registro inserido com sucesso: 10143091
Registro inserido com sucesso: 10143285
Registro inserido com sucesso: 10141560
Registro inserido com sucesso: 10142072
Registro inserido com sucesso: 10142286
Registro inserido com sucesso: 10142466
Registro inserido com sucesso: 10143067
Registro inserido com sucesso: 10143595
Registro inserido com sucesso: 10141943
Registro inserido com sucesso: 10142584
Registro inserido com sucesso: 10142721
Registro inserido com sucesso: 10142873
Registro inserido com sucesso: 10142962
Registro inserido com sucesso: 10143032
Registro inserido com sucesso: 10143327
Registro inserido com sucesso: 10143422
Registro inserido com sucesso: 10143398
Registro inserido com sucesso: 10141802
Registro inserido com sucesso: 10142099
Registro inserido com sucesso: 10142808
Registro inserido com sucesso: 10142144
Registro inserido com sucesso: 10142624
Registro inserido com sucesso: 10142942
Registro inserido com sucesso: 10143263
Registro inserido com sucesso: 10141646
Registro inserido com sucesso: 10141794
Registro inserido com sucesso: 10141954
Registro inserido com sucesso: 10142100
Registro inserido com sucesso: 10142129
Registro inserido com sucesso: 10142800
Registro inserido com sucesso: 10143147
Registro inserido com sucesso: 10143574
Registro inserido com sucesso: 10141625
Registro inserido com sucesso: 10142068
Registro inserido com sucesso: 10143044
Registro inserido com sucesso: 10143541
Registro inserido com sucesso: 10143596
Registro inserido com sucesso: 10141718
Registro inserido com sucesso: 10142795
Registro inserido com sucesso: 10143223
Registro inserido com sucesso: 10142005
Registro inserido com sucesso: 10142480
Registro inserido com sucesso: 10142955
Registro inserido com sucesso: 10143281
Registro inserido com sucesso: 10143585
Registro inserido com sucesso: 10141583
Registro inserido com sucesso: 10141657
Registro inserido com sucesso: 10141793
Registro inserido com sucesso: 10142364
Registro inserido com sucesso: 10142879
Registro inserido com sucesso: 10142892
Registro inserido com sucesso: 10143407
Registro inserido com sucesso: 10143591
Registro inserido com sucesso: 10142361
Registro inserido com sucesso: 10142952
Registro inserido com sucesso: 10143426
Registro inserido com sucesso: 10141618
Registro inserido com sucesso: 10141889
Registro inserido com sucesso: 10142235
Registro inserido com sucesso: 10142807
Registro inserido com sucesso: 10143036
Registro inserido com sucesso: 10143575
Registro inserido com sucesso: 10141542
Registro inserido com sucesso: 10141685
Registro inserido com sucesso: 10141726
Registro inserido com sucesso: 10141759
Registro inserido com sucesso: 10142077
Registro inserido com sucesso: 10142124
Registro inserido com sucesso: 10143353
Registro inserido com sucesso: 10141945
Registro inserido com sucesso: 10142043
Registro inserido com sucesso: 10142519
Registro inserido com sucesso: 10143475
Registro inserido com sucesso: 10143613
Registro inserido com sucesso: 10141527
Registro inserido com sucesso: 10142256
Registro inserido com sucesso: 10142817
Registro inserido com sucesso: 10143268
Registro inserido com sucesso: 10142230
Registro inserido com sucesso: 10143202
Registro inserido com sucesso: 10141798
Registro inserido com sucesso: 10141941
Registro inserido com sucesso: 10143372
Registro inserido com sucesso: 10143402
Registro inserido com sucesso: 10141552
Registro inserido com sucesso: 10141891
Registro inserido com sucesso: 10142713
Registro inserido com sucesso: 10143496
Registro inserido com sucesso: 10141755
Registro inserido com sucesso: 10142805
Registro inserido com sucesso: 10141723
Registro inserido com sucesso: 10141936
Registro inserido com sucesso: 10142075
Registro inserido com sucesso: 10142086
Registro inserido com sucesso: 10142809
Registro inserido com sucesso: 10141983
Registro inserido com sucesso: 10142070
Registro inserido com sucesso: 10142538
Registro inserido com sucesso: 10142793
Registro inserido com sucesso: 10143035
Registro inserido com sucesso: 10143236
Registro inserido com sucesso: 10143352
Registro inserido com sucesso: 10143355
Registro inserido com sucesso: 10142052
Registro inserido com sucesso: 10142339
Registro inserido com sucesso: 10142426
Registro inserido com sucesso: 10142894
Registro inserido com sucesso: 10143172
Registro inserido com sucesso: 10143256
Registro inserido com sucesso: 10143336
Registro inserido com sucesso: 10142107
Registro inserido com sucesso: 10141878
Registro inserido com sucesso: 10141958
Registro inserido com sucesso: 10142427
Registro inserido com sucesso: 10141845
Registro inserido com sucesso: 10141952
Registro inserido com sucesso: 10142693
Registro inserido com sucesso: 10141513
Registro inserido com sucesso: 10141579
Registro inserido com sucesso: 10141801
Registro inserido com sucesso: 10141940
Registro inserido com sucesso: 10143108
Registro inserido com sucesso: 10143247
Registro inserido com sucesso: 10143539
Registro inserido com sucesso: 10141509
Registro inserido com sucesso: 10142233
Registro inserido com sucesso: 10142448
Registro inserido com sucesso: 10142741
Registro inserido com sucesso: 10142786
Registro inserido com sucesso: 10142791
Registro inserido com sucesso: 10142968
Registro inserido com sucesso: 10141504
Registro inserido com sucesso: 10141607
Registro inserido com sucesso: 10141999
Registro inserido com sucesso: 10142201
Registro inserido com sucesso: 10142266
Registro inserido com sucesso: 10142925
Registro inserido com sucesso: 10143169
Registro inserido com sucesso: 10142529
Registro inserido com sucesso: 10142799
Registro inserido com sucesso: 10143015
Registro inserido com sucesso: 10143447
Registro inserido com sucesso: 10143495
Registro inserido com sucesso: 10141523
Registro inserido com sucesso: 10141996
Registro inserido com sucesso: 10142089
Registro inserido com sucesso: 10142145
Registro inserido com sucesso: 10142520
Registro inserido com sucesso: 10143160
Registro inserido com sucesso: 10142653
Registro inserido com sucesso: 10143126
Registro inserido com sucesso: 10141884
Registro inserido com sucesso: 10141920
Registro inserido com sucesso: 10142076
Registro inserido com sucesso: 10141524
Registro inserido com sucesso: 10141633
Registro inserido com sucesso: 10142293
Registro inserido com sucesso: 10143602
Registro inserido com sucesso: 10141514
Registro inserido com sucesso: 10141661
Registro inserido com sucesso: 10142326
Registro inserido com sucesso: 10142648
Registro inserido com sucesso: 10141587
Registro inserido com sucesso: 10141630
Registro inserido com sucesso: 10142002
Registro inserido com sucesso: 10142503
Registro inserido com sucesso: 10142625
Registro inserido com sucesso: 10142961
Registro inserido com sucesso: 10143252
Registro inserido com sucesso: 10143356
Registro inserido com sucesso: 10143400
Registro inserido com sucesso: 10143512
Registro inserido com sucesso: 10141742
Registro inserido com sucesso: 10143440
Registro inserido com sucesso: 10141532
Registro inserido com sucesso: 10141563
Registro inserido com sucesso: 10141658
Registro inserido com sucesso: 10142121
Registro inserido com sucesso: 10142491
Registro inserido com sucesso: 10142639
Registro inserido com sucesso: 10142716
Registro inserido com sucesso: 10142887
Registro inserido com sucesso: 10142926
Registro inserido com sucesso: 10143321
Registro inserido com sucesso: 10143403
Registro inserido com sucesso: 10143491
Registro inserido com sucesso: 10141508
Registro inserido com sucesso: 10141817
Registro inserido com sucesso: 10142030
Registro inserido com sucesso: 10142178
Registro inserido com sucesso: 10143005
Registro inserido com sucesso: 10143564
Registro inserido com sucesso: 10141695
Registro inserido com sucesso: 10141724
Registro inserido com sucesso: 10141740
Registro inserido com sucesso: 10141796
Registro inserido com sucesso: 10141811
Registro inserido com sucesso: 10142891
Registro inserido com sucesso: 10141536
Registro inserido com sucesso: 10141654
Registro inserido com sucesso: 10141871
Registro inserido com sucesso: 10141997
Registro inserido com sucesso: 10142139
Registro inserido com sucesso: 10142695
Registro inserido com sucesso: 10142930
Registro inserido com sucesso: 10143257
Registro inserido com sucesso: 10143567
Registro inserido com sucesso: 10141540
Registro inserido com sucesso: 10141667
Registro inserido com sucesso: 10142410
Registro inserido com sucesso: 10142468
Registro inserido com sucesso: 10142858
Registro inserido com sucesso: 10142995
Registro inserido com sucesso: 10143260
Registro inserido com sucesso: 10143399
Registro inserido com sucesso: 10141622
Registro inserido com sucesso: 10141680
Registro inserido com sucesso: 10141813
Registro inserido com sucesso: 10142271
Registro inserido com sucesso: 10142409
Registro inserido com sucesso: 10142558
Registro inserido com sucesso: 10143376
Registro inserido com sucesso: 10143492
Registro inserido com sucesso: 10141608
Registro inserido com sucesso: 10141815
Registro inserido com sucesso: 10141962
Registro inserido com sucesso: 10142137
Registro inserido com sucesso: 10142275
Registro inserido com sucesso: 10142315
Registro inserido com sucesso: 10142818
Registro inserido com sucesso: 10142993
Registro inserido com sucesso: 10143454
Registro inserido com sucesso: 10142057
Registro inserido com sucesso: 10142101
Registro inserido com sucesso: 10142629
Registro inserido com sucesso: 10142849
Registro inserido com sucesso: 10142973
Registro inserido com sucesso: 10143111
Registro inserido com sucesso: 10143614
Registro inserido com sucesso: 10141582
Registro inserido com sucesso: 10142028
Registro inserido com sucesso: 10142452
Registro inserido com sucesso: 10143075
Registro inserido com sucesso: 10143273
Registro inserido com sucesso: 10143371
Registro inserido com sucesso: 10141748
Registro inserido com sucesso: 10141951
Registro inserido com sucesso: 10142327
Registro inserido com sucesso: 10142900
Registro inserido com sucesso: 10143043
Registro inserido com sucesso: 10143275
Registro inserido com sucesso: 10143411
Registro inserido com sucesso: 10143499
Registro inserido com sucesso: 10143515
Registro inserido com sucesso: 10141505
Registro inserido com sucesso: 10141640
Registro inserido com sucesso: 10142580
Registro inserido com sucesso: 10142603
Registro inserido com sucesso: 10142915
Registro inserido com sucesso: 10142020
Registro inserido com sucesso: 10142211
Registro inserido com sucesso: 10142252
Registro inserido com sucesso: 10142277
Registro inserido com sucesso: 10142278
Registro inserido com sucesso: 10142411
Registro inserido com sucesso: 10141599
Registro inserido com sucesso: 10142255
Registro inserido com sucesso: 10142467
Registro inserido com sucesso: 10142582
Registro inserido com sucesso: 10142675
Registro inserido com sucesso: 10143453
Registro inserido com sucesso: 10142097
Registro inserido com sucesso: 10142701
Registro inserido com sucesso: 10142823
Registro inserido com sucesso: 10143360
Registro inserido com sucesso: 10143364
Registro inserido com sucesso: 10143434
Registro inserido com sucesso: 10141683
Registro inserido com sucesso: 10141850
Registro inserido com sucesso: 10142062
Registro inserido com sucesso: 10142430
Registro inserido com sucesso: 10142484
Registro inserido com sucesso: 10142541
Registro inserido com sucesso: 10142680
Registro inserido com sucesso: 10143523
Registro inserido com sucesso: 10142023
Registro inserido com sucesso: 10142061
Registro inserido com sucesso: 10142545
Registro inserido com sucesso: 10143092
Registro inserido com sucesso: 10141598
Registro inserido com sucesso: 10141678
Registro inserido com sucesso: 10142055
Registro inserido com sucesso: 10142192
Registro inserido com sucesso: 10142345
Registro inserido com sucesso: 10141595
Registro inserido com sucesso: 10142574
Registro inserido com sucesso: 10142679
Registro inserido com sucesso: 10142945
Registro inserido com sucesso: 10143020
Registro inserido com sucesso: 10143069
Registro inserido com sucesso: 10143107
Registro inserido com sucesso: 10143393
Registro inserido com sucesso: 10141501
Registro inserido com sucesso: 10142417
Registro inserido com sucesso: 10142861
Registro inserido com sucesso: 10143122
Registro inserido com sucesso: 10143522
Registro inserido com sucesso: 10142006
Registro inserido com sucesso: 10142151
Registro inserido com sucesso: 10142354
Registro inserido com sucesso: 10143274
Registro inserido com sucesso: 10141907
Registro inserido com sucesso: 10142008
Registro inserido com sucesso: 10142177
Registro inserido com sucesso: 10142295
Registro inserido com sucesso: 10142341
Registro inserido com sucesso: 10142443
Registro inserido com sucesso: 10142734
Registro inserido com sucesso: 10142902
Registro inserido com sucesso: 10143245
Registro inserido com sucesso: 10141614
Registro inserido com sucesso: 10141690
Registro inserido com sucesso: 10142482
Registro inserido com sucesso: 10143021
Registro inserido com sucesso: 10143155
Registro inserido com sucesso: 10143317
Registro inserido com sucesso: 10143404
Registro inserido com sucesso: 10143620
Registro inserido com sucesso: 10141669
Registro inserido com sucesso: 10141960
Registro inserido com sucesso: 10142182
Registro inserido com sucesso: 10142248
Registro inserido com sucesso: 10142880
Registro inserido com sucesso: 10142949
Registro inserido com sucesso: 10143243
Registro inserido com sucesso: 10143332
Registro inserido com sucesso: 10143540
Registro inserido com sucesso: 10143576
Registro inserido com sucesso: 10141517
Registro inserido com sucesso: 10141559
Registro inserido com sucesso: 10141648
Registro inserido com sucesso: 10141741
Registro inserido com sucesso: 10142019
Registro inserido com sucesso: 10142059
Registro inserido com sucesso: 10142236
Registro inserido com sucesso: 10142306
Registro inserido com sucesso: 10142309
Registro inserido com sucesso: 10143343
Registro inserido com sucesso: 10143514
Registro inserido com sucesso: 10141512
Registro inserido com sucesso: 10141589
Registro inserido com sucesso: 10141637
Registro inserido com sucesso: 10142677
Registro inserido com sucesso: 10142149
Registro inserido com sucesso: 10142730
Registro inserido com sucesso: 10143248
Registro inserido com sucesso: 10141769
Registro inserido com sucesso: 10142031
Registro inserido com sucesso: 10142204
Registro inserido com sucesso: 10142395
Registro inserido com sucesso: 10142632
Registro inserido com sucesso: 10142392
Registro inserido com sucesso: 10142650
Registro inserido com sucesso: 10142706
Registro inserido com sucesso: 10142850
Registro inserido com sucesso: 10142947
Registro inserido com sucesso: 10143536
Registro inserido com sucesso: 10141788
Registro inserido com sucesso: 10142432
Registro inserido com sucesso: 10142946
Registro inserido com sucesso: 10142970
Registro inserido com sucesso: 10141550
Registro inserido com sucesso: 10141751
Registro inserido com sucesso: 10141913
Registro inserido com sucesso: 10142780
Registro inserido com sucesso: 10142848
Registro inserido com sucesso: 10142874
Registro inserido com sucesso: 10142958
Registro inserido com sucesso: 10143176
Registro inserido com sucesso: 10143347
Registro inserido com sucesso: 10141632
Registro inserido com sucesso: 10141688
Registro inserido com sucesso: 10141727
Registro inserido com sucesso: 10141982
Registro inserido com sucesso: 10142078
Registro inserido com sucesso: 10142579
Registro inserido com sucesso: 10142829
Registro inserido com sucesso: 10141948
Registro inserido com sucesso: 10142048
Registro inserido com sucesso: 10142065
Registro inserido com sucesso: 10142229
Registro inserido com sucesso: 10143566
Registro inserido com sucesso: 10143600
Registro inserido com sucesso: 10141526
Registro inserido com sucesso: 10141605
Registro inserido com sucesso: 10141609
Registro inserido com sucesso: 10142249
Registro inserido com sucesso: 10142282
Registro inserido com sucesso: 10142602
Registro inserido com sucesso: 10143026
Registro inserido com sucesso: 10143292
Registro inserido com sucesso: 10141712
Registro inserido com sucesso: 10141987
Registro inserido com sucesso: 10142093
Registro inserido com sucesso: 10142325
Registro inserido com sucesso: 10142552
Registro inserido com sucesso: 10142598
Registro inserido com sucesso: 10143013
Registro inserido com sucesso: 10141641
Registro inserido com sucesso: 10141787
Registro inserido com sucesso: 10142697
Registro inserido com sucesso: 10142866

Pronto! Ja inserimos os registros de fabricante na tabela no banco. Agora vamos ler um sql da tabela do banco e adiciona-lo em um dataframe.

## Adicionar Dados a um dataframe

> Data Frame de Clima

In [ ]:
df_clima = pd.read_sql('clima', con=conn) # Lê o dado na tabela do banco de dados
df_clima

   cod_clima     clima
0          1    quente
1          2  moderado
2          3      frio

In [ ]:
dict_climas = df_clima.set_index(df_clima.clima)['cod_clima'].to_dict()
dict_climas

{'quente': 1, 'moderado': 2, 'frio': 3}

> Data Frame de Hobbies

In [ ]:
df_hobbie = pd.read_sql('hobbie', con=conn) # Lê o dado na tabela do banco de dados
df_hobbie

   cod_hobbie              hobbie
0           1      Escutar música
1           2    Praticar esporte
2           3  Aprender algo novo
3           4      Pintar quadros
4           5              Dormir
5           6            Escrever
6           7         Assistir TV
7           8          Ler livros

In [ ]:
dict_hobbies = df_hobbie.set_index(df_hobbie.hobbie)['cod_hobbie'].to_dict()
dict_hobbies

{'Escutar música': 1,
 'Praticar esporte': 2,
 'Aprender algo novo': 3,
 'Pintar quadros': 4,
 'Dormir': 5,
 'Escrever': 6,
 'Assistir TV': 7,
 'Ler livros': 8}

> Data Frame de bebidas

In [ ]:
df_bebida = pd.read_sql('bebida', con=conn) # Lê o dado na tabela do banco de dados
df_bebida

   cod_bebida        bebida
0           1  refrigerante
1           2         Vinho
2           3           Chá
3           4          Café
4           5       Cerveja
5           6          Água

In [ ]:
dict_bebidas = df_bebida.set_index(df_bebida.bebida)['cod_bebida'].to_dict()
dict_bebidas

{'refrigerante': 1, 'Vinho': 2, 'Chá': 3, 'Café': 4, 'Cerveja': 5, 'Água': 6}

> Data Frame de Pessoas

In [ ]:
df_pessoas = pd.read_sql('pessoa', con=conn) # Lê o dado na tabela do banco de dados

In [ ]:
df_pessoas

      cod_pessoa     genero data_nascimento
0       10141501   Feminino      1984-05-22
1       10141502  Masculino      1998-06-27
2       10141503  Masculino      1963-02-18
3       10141504  Masculino      1979-09-09
4       10141505  Masculino      1958-10-04
...          ...        ...             ...
2122    10143623  Masculino      1975-07-16
2123    10143624  Masculino      1959-04-01
2124    10143625  Masculino      1994-05-13
2125    10143626  Masculino      1956-09-08
2126    10143627  Masculino      1963-06-16

[2127 rows x 3 columns]

Perceba que agora temos o código associado a uma pessoa. Esse código será utilizado para popular a tabela de pessoas.

> *Vamos ler todo o dado contido na coluna de cod_pessoa do dataframe **df_pessoas** e buscar a sua equivalencia no dataframe **df_pesquisa***

In [ ]:
df_animais = pd.read_sql('animal_estimacao', con=conn) # Lê o dado na tabela do banco de dados

In [ ]:
df_animais

   cod_animal_estimacao     animal
0                     1      peixe
1                     2       gato
2                     3   cachorro
3                     4  tartaruga

Perceba que agora temos o código associado a um animal de estimação. Esse código será utilizado para popular a tabela de pessoas.

> *Vamos ler todo o dado contido na coluna de animal_estimacao do dataframe **df_animais** e buscar a sua equivalencia no dataframe **df_pesquisa***

 Primeiro vamos setar a coluna nome do animal como index. Essa coluna vai ser utilizada como index para buscar os dados no dataframe df_pesquisa. Após isso, vamos transformar em um dicionário

In [ ]:
dict_animais = df_animais.set_index(df_animais.animal)['cod_animal_estimacao'].to_dict()
dict_animais

{'peixe': 1, 'gato': 2, 'cachorro': 3, 'tartaruga': 4}

In [ ]:
dict_pessoas = df_pessoas.set_index(df_pessoas.cod_pessoa)['cod_pessoa'].to_dict()
dict_pessoas

{10141501: 10141501,
 10141502: 10141502,
 10141503: 10141503,
 10141504: 10141504,
 10141505: 10141505,
 10141506: 10141506,
 10141507: 10141507,
 10141508: 10141508,
 10141509: 10141509,
 10141510: 10141510,
 10141511: 10141511,
 10141512: 10141512,
 10141513: 10141513,
 10141514: 10141514,
 10141515: 10141515,
 10141516: 10141516,
 10141517: 10141517,
 10141518: 10141518,
 10141519: 10141519,
 10141520: 10141520,
 10141521: 10141521,
 10141522: 10141522,
 10141523: 10141523,
 10141524: 10141524,
 10141525: 10141525,
 10141526: 10141526,
 10141527: 10141527,
 10141528: 10141528,
 10141529: 10141529,
 10141530: 10141530,
 10141531: 10141531,
 10141532: 10141532,
 10141533: 10141533,
 10141534: 10141534,
 10141535: 10141535,
 10141536: 10141536,
 10141537: 10141537,
 10141538: 10141538,
 10141539: 10141539,
 10141540: 10141540,
 10141541: 10141541,
 10141542: 10141542,
 10141543: 10141543,
 10141544: 10141544,
 10141545: 10141545,
 10141546: 10141546,
 10141547: 10141547,
 10141548: 10141548,
 10141549: 10141549,
 10141550: 10141550,
 10141551: 10141551,
 10141552: 10141552,
 10141553: 10141553,
 10141554: 10141554,
 10141555: 10141555,
 10141556: 10141556,
 10141557: 10141557,
 10141558: 10141558,
 10141559: 10141559,
 10141560: 10141560,
 10141561: 10141561,
 10141562: 10141562,
 10141563: 10141563,
 10141564: 10141564,
 10141565: 10141565,
 10141566: 10141566,
 10141567: 10141567,
 10141568: 10141568,
 10141569: 10141569,
 10141570: 10141570,
 10141571: 10141571,
 10141572: 10141572,
 10141573: 10141573,
 10141574: 10141574,
 10141575: 10141575,
 10141576: 10141576,
 10141577: 10141577,
 10141578: 10141578,
 10141579: 10141579,
 10141580: 10141580,
 10141581: 10141581,
 10141582: 10141582,
 10141583: 10141583,
 10141584: 10141584,
 10141585: 10141585,
 10141586: 10141586,
 10141587: 10141587,
 10141588: 10141588,
 10141589: 10141589,
 10141590: 10141590,
 10141591: 10141591,
 10141592: 10141592,
 10141593: 10141593,
 10141594: 10141594,
 10141595: 10141595,
 10141596: 10141596,
 10141597: 10141597,
 10141598: 10141598,
 10141599: 10141599,
 10141600: 10141600,
 10141601: 10141601,
 10141602: 10141602,
 10141603: 10141603,
 10141604: 10141604,
 10141605: 10141605,
 10141606: 10141606,
 10141607: 10141607,
 10141608: 10141608,
 10141609: 10141609,
 10141610: 10141610,
 10141611: 10141611,
 10141612: 10141612,
 10141613: 10141613,
 10141614: 10141614,
 10141615: 10141615,
 10141616: 10141616,
 10141617: 10141617,
 10141618: 10141618,
 10141619: 10141619,
 10141620: 10141620,
 10141621: 10141621,
 10141622: 10141622,
 10141623: 10141623,
 10141624: 10141624,
 10141625: 10141625,
 10141626: 10141626,
 10141627: 10141627,
 10141628: 10141628,
 10141629: 10141629,
 10141630: 10141630,
 10141631: 10141631,
 10141632: 10141632,
 10141633: 10141633,
 10141634: 10141634,
 10141635: 10141635,
 10141636: 10141636,
 10141637: 10141637,
 10141638: 10141638,
 10141639: 10141639,
 10141640: 10141640,
 10141641: 10141641,
 10141642: 10141642,
 10141643: 10141643,
 10141644: 10141644,
 10141645: 10141645,
 10141646: 10141646,
 10141647: 10141647,
 10141648: 10141648,
 10141649: 10141649,
 10141650: 10141650,
 10141651: 10141651,
 10141652: 10141652,
 10141653: 10141653,
 10141654: 10141654,
 10141655: 10141655,
 10141656: 10141656,
 10141657: 10141657,
 10141658: 10141658,
 10141659: 10141659,
 10141660: 10141660,
 10141661: 10141661,
 10141662: 10141662,
 10141663: 10141663,
 10141664: 10141664,
 10141665: 10141665,
 10141666: 10141666,
 10141667: 10141667,
 10141668: 10141668,
 10141669: 10141669,
 10141670: 10141670,
 10141671: 10141671,
 10141672: 10141672,
 10141673: 10141673,
 10141674: 10141674,
 10141675: 10141675,
 10141676: 10141676,
 10141677: 10141677,
 10141678: 10141678,
 10141679: 10141679,
 10141680: 10141680,
 10141681: 10141681,
 10141682: 10141682,
 10141683: 10141683,
 10141684: 10141684,
 10141685: 10141685,
 10141686: 10141686,
 10141687: 10141687,
 10141688: 10141688,
 10141689: 10141689,
 10141690: 10141690,
 10141691: 10141691,
 10141692: 10141692,
 10141693: 10141693,
 10141694: 10141694,
 10141695: 10141695,
 10141696: 10141696,
 10141697: 10141697,
 10141698: 10141698,
 10141699: 10141699,
 10141700: 10141700,
 10141701: 10141701,
 10141702: 10141702,
 10141703: 10141703,
 10141704: 10141704,
 10141705: 10141705,
 10141706: 10141706,
 10141707: 10141707,
 10141708: 10141708,
 10141709: 10141709,
 10141710: 10141710,
 10141711: 10141711,
 10141712: 10141712,
 10141713: 10141713,
 10141714: 10141714,
 10141715: 10141715,
 10141716: 10141716,
 10141717: 10141717,
 10141718: 10141718,
 10141719: 10141719,
 10141720: 10141720,
 10141721: 10141721,
 10141722: 10141722,
 10141723: 10141723,
 10141724: 10141724,
 10141725: 10141725,
 10141726: 10141726,
 10141727: 10141727,
 10141728: 10141728,
 10141729: 10141729,
 10141730: 10141730,
 10141731: 10141731,
 10141732: 10141732,
 10141733: 10141733,
 10141734: 10141734,
 10141735: 10141735,
 10141736: 10141736,
 10141737: 10141737,
 10141738: 10141738,
 10141739: 10141739,
 10141740: 10141740,
 10141741: 10141741,
 10141742: 10141742,
 10141743: 10141743,
 10141744: 10141744,
 10141745: 10141745,
 10141746: 10141746,
 10141747: 10141747,
 10141748: 10141748,
 10141749: 10141749,
 10141750: 10141750,
 10141751: 10141751,
 10141752: 10141752,
 10141753: 10141753,
 10141754: 10141754,
 10141755: 10141755,
 10141756: 10141756,
 10141757: 10141757,
 10141758: 10141758,
 10141759: 10141759,
 10141760: 10141760,
 10141761: 10141761,
 10141762: 10141762,
 10141763: 10141763,
 10141764: 10141764,
 10141765: 10141765,
 10141766: 10141766,
 10141767: 10141767,
 10141768: 10141768,
 10141769: 10141769,
 10141770: 10141770,
 10141771: 10141771,
 10141772: 10141772,
 10141773: 10141773,
 10141774: 10141774,
 10141775: 10141775,
 10141776: 10141776,
 10141777: 10141777,
 10141778: 10141778,
 10141779: 10141779,
 10141780: 10141780,
 10141781: 10141781,
 10141782: 10141782,
 10141783: 10141783,
 10141784: 10141784,
 10141785: 10141785,
 10141786: 10141786,
 10141787: 10141787,
 10141788: 10141788,
 10141789: 10141789,
 10141790: 10141790,
 10141791: 10141791,
 10141792: 10141792,
 10141793: 10141793,
 10141794: 10141794,
 10141795: 10141795,
 10141796: 10141796,
 10141797: 10141797,
 10141798: 10141798,
 10141799: 10141799,
 10141800: 10141800,
 10141801: 10141801,
 10141802: 10141802,
 10141803: 10141803,
 10141804: 10141804,
 10141805: 10141805,
 10141806: 10141806,
 10141807: 10141807,
 10141808: 10141808,
 10141809: 10141809,
 10141810: 10141810,
 10141811: 10141811,
 10141812: 10141812,
 10141813: 10141813,
 10141814: 10141814,
 10141815: 10141815,
 10141816: 10141816,
 10141817: 10141817,
 10141818: 10141818,
 10141819: 10141819,
 10141820: 10141820,
 10141821: 10141821,
 10141822: 10141822,
 10141823: 10141823,
 10141824: 10141824,
 10141825: 10141825,
 10141826: 10141826,
 10141827: 10141827,
 10141828: 10141828,
 10141829: 10141829,
 10141830: 10141830,
 10141831: 10141831,
 10141832: 10141832,
 10141833: 10141833,
 10141834: 10141834,
 10141835: 10141835,
 10141836: 10141836,
 10141837: 10141837,
 10141838: 10141838,
 10141839: 10141839,
 10141840: 10141840,
 10141841: 10141841,
 10141842: 10141842,
 10141843: 10141843,
 10141844: 10141844,
 10141845: 10141845,
 10141846: 10141846,
 10141847: 10141847,
 10141848: 10141848,
 10141849: 10141849,
 10141850: 10141850,
 10141851: 10141851,
 10141852: 10141852,
 10141853: 10141853,
 10141854: 10141854,
 10141855: 10141855,
 10141856: 10141856,
 10141857: 10141857,
 10141858: 10141858,
 10141859: 10141859,
 10141860: 10141860,
 10141861: 10141861,
 10141862: 10141862,
 10141863: 10141863,
 10141864: 10141864,
 10141865: 10141865,
 10141866: 10141866,
 10141867: 10141867,
 10141868: 10141868,
 10141869: 10141869,
 10141870: 10141870,
 10141871: 10141871,
 10141872: 10141872,
 10141873: 10141873,
 10141874: 10141874,
 10141875: 10141875,
 10141876: 10141876,
 10141877: 10141877,
 10141878: 10141878,
 10141879: 10141879,
 10141880: 10141880,
 10141881: 10141881,
 10141882: 10141882,
 10141883: 10141883,
 10141884: 10141884,
 10141885: 10141885,
 10141886: 10141886,
 10141887: 10141887,
 10141888: 10141888,
 10141889: 10141889,
 10141890: 10141890,
 10141891: 10141891,
 10141892: 10141892,
 10141893: 10141893,
 10141894: 10141894,
 10141895: 10141895,
 10141896: 10141896,
 10141897: 10141897,
 10141898: 10141898,
 10141899: 10141899,
 10141900: 10141900,
 10141901: 10141901,
 10141902: 10141902,
 10141903: 10141903,
 10141904: 10141904,
 10141905: 10141905,
 10141906: 10141906,
 10141907: 10141907,
 10141908: 10141908,
 10141909: 10141909,
 10141910: 10141910,
 10141911: 10141911,
 10141912: 10141912,
 10141913: 10141913,
 10141914: 10141914,
 10141915: 10141915,
 10141916: 10141916,
 10141917: 10141917,
 10141918: 10141918,
 10141919: 10141919,
 10141920: 10141920,
 10141921: 10141921,
 10141922: 10141922,
 10141923: 10141923,
 10141924: 10141924,
 10141925: 10141925,
 10141926: 10141926,
 10141927: 10141927,
 10141928: 10141928,
 10141929: 10141929,
 10141930: 10141930,
 10141931: 10141931,
 10141932: 10141932,
 10141933: 10141933,
 10141934: 10141934,
 10141935: 10141935,
 10141936: 10141936,
 10141937: 10141937,
 10141938: 10141938,
 10141939: 10141939,
 10141940: 10141940,
 10141941: 10141941,
 10141942: 10141942,
 10141943: 10141943,
 10141944: 10141944,
 10141945: 10141945,
 10141946: 10141946,
 10141947: 10141947,
 10141948: 10141948,
 10141949: 10141949,
 10141950: 10141950,
 10141951: 10141951,
 10141952: 10141952,
 10141953: 10141953,
 10141954: 10141954,
 10141955: 10141955,
 10141956: 10141956,
 10141957: 10141957,
 10141958: 10141958,
 10141959: 10141959,
 10141960: 10141960,
 10141961: 10141961,
 10141962: 10141962,
 10141963: 10141963,
 10141964: 10141964,
 10141965: 10141965,
 10141966: 10141966,
 10141967: 10141967,
 10141968: 10141968,
 10141969: 10141969,
 10141970: 10141970,
 10141971: 10141971,
 10141972: 10141972,
 10141973: 10141973,
 10141974: 10141974,
 10141975: 10141975,
 10141976: 10141976,
 10141977: 10141977,
 10141978: 10141978,
 10141979: 10141979,
 10141980: 10141980,
 10141981: 10141981,
 10141982: 10141982,
 10141983: 10141983,
 10141984: 10141984,
 10141985: 10141985,
 10141986: 10141986,
 10141987: 10141987,
 10141988: 10141988,
 10141989: 10141989,
 10141990: 10141990,
 10141991: 10141991,
 10141992: 10141992,
 10141993: 10141993,
 10141994: 10141994,
 10141995: 10141995,
 10141996: 10141996,
 10141997: 10141997,
 10141998: 10141998,
 10141999: 10141999,
 10142000: 10142000,
 10142001: 10142001,
 10142002: 10142002,
 10142003: 10142003,
 10142004: 10142004,
 10142005: 10142005,
 10142006: 10142006,
 10142007: 10142007,
 10142008: 10142008,
 10142009: 10142009,
 10142010: 10142010,
 10142011: 10142011,
 10142012: 10142012,
 10142013: 10142013,
 10142014: 10142014,
 10142015: 10142015,
 10142016: 10142016,
 10142017: 10142017,
 10142018: 10142018,
 10142019: 10142019,
 10142020: 10142020,
 10142021: 10142021,
 10142022: 10142022,
 10142023: 10142023,
 10142024: 10142024,
 10142025: 10142025,
 10142026: 10142026,
 10142027: 10142027,
 10142028: 10142028,
 10142029: 10142029,
 10142030: 10142030,
 10142031: 10142031,
 10142032: 10142032,
 10142033: 10142033,
 10142034: 10142034,
 10142035: 10142035,
 10142036: 10142036,
 10142037: 10142037,
 10142038: 10142038,
 10142039: 10142039,
 10142040: 10142040,
 10142041: 10142041,
 10142042: 10142042,
 10142043: 10142043,
 10142044: 10142044,
 10142045: 10142045,
 10142046: 10142046,
 10142047: 10142047,
 10142048: 10142048,
 10142049: 10142049,
 10142050: 10142050,
 10142051: 10142051,
 10142052: 10142052,
 10142053: 10142053,
 10142054: 10142054,
 10142055: 10142055,
 10142056: 10142056,
 10142057: 10142057,
 10142058: 10142058,
 10142059: 10142059,
 10142060: 10142060,
 10142061: 10142061,
 10142062: 10142062,
 10142063: 10142063,
 10142064: 10142064,
 10142065: 10142065,
 10142066: 10142066,
 10142067: 10142067,
 10142068: 10142068,
 10142069: 10142069,
 10142070: 10142070,
 10142071: 10142071,
 10142072: 10142072,
 10142073: 10142073,
 10142074: 10142074,
 10142075: 10142075,
 10142076: 10142076,
 10142077: 10142077,
 10142078: 10142078,
 10142079: 10142079,
 10142080: 10142080,
 10142081: 10142081,
 10142082: 10142082,
 10142083: 10142083,
 10142084: 10142084,
 10142085: 10142085,
 10142086: 10142086,
 10142087: 10142087,
 10142088: 10142088,
 10142089: 10142089,
 10142090: 10142090,
 10142091: 10142091,
 10142092: 10142092,
 10142093: 10142093,
 10142094: 10142094,
 10142095: 10142095,
 10142096: 10142096,
 10142097: 10142097,
 10142098: 10142098,
 10142099: 10142099,
 10142100: 10142100,
 10142101: 10142101,
 10142102: 10142102,
 10142103: 10142103,
 10142104: 10142104,
 10142105: 10142105,
 10142106: 10142106,
 10142107: 10142107,
 10142108: 10142108,
 10142109: 10142109,
 10142110: 10142110,
 10142111: 10142111,
 10142112: 10142112,
 10142113: 10142113,
 10142114: 10142114,
 10142115: 10142115,
 10142116: 10142116,
 10142117: 10142117,
 10142118: 10142118,
 10142119: 10142119,
 10142120: 10142120,
 10142121: 10142121,
 10142122: 10142122,
 10142123: 10142123,
 10142124: 10142124,
 10142125: 10142125,
 10142126: 10142126,
 10142127: 10142127,
 10142128: 10142128,
 10142129: 10142129,
 10142130: 10142130,
 10142131: 10142131,
 10142132: 10142132,
 10142133: 10142133,
 10142134: 10142134,
 10142135: 10142135,
 10142136: 10142136,
 10142137: 10142137,
 10142138: 10142138,
 10142139: 10142139,
 10142140: 10142140,
 10142141: 10142141,
 10142142: 10142142,
 10142143: 10142143,
 10142144: 10142144,
 10142145: 10142145,
 10142146: 10142146,
 10142147: 10142147,
 10142148: 10142148,
 10142149: 10142149,
 10142150: 10142150,
 10142151: 10142151,
 10142152: 10142152,
 10142153: 10142153,
 10142154: 10142154,
 10142155: 10142155,
 10142156: 10142156,
 10142157: 10142157,
 10142158: 10142158,
 10142159: 10142159,
 10142160: 10142160,
 10142161: 10142161,
 10142162: 10142162,
 10142163: 10142163,
 10142164: 10142164,
 10142165: 10142165,
 10142166: 10142166,
 10142167: 10142167,
 10142168: 10142168,
 10142169: 10142169,
 10142170: 10142170,
 10142171: 10142171,
 10142172: 10142172,
 10142173: 10142173,
 10142174: 10142174,
 10142175: 10142175,
 10142176: 10142176,
 10142177: 10142177,
 10142178: 10142178,
 10142179: 10142179,
 10142180: 10142180,
 10142181: 10142181,
 10142182: 10142182,
 10142183: 10142183,
 10142184: 10142184,
 10142185: 10142185,
 10142186: 10142186,
 10142187: 10142187,
 10142188: 10142188,
 10142189: 10142189,
 10142190: 10142190,
 10142191: 10142191,
 10142192: 10142192,
 10142193: 10142193,
 10142194: 10142194,
 10142195: 10142195,
 10142196: 10142196,
 10142197: 10142197,
 10142198: 10142198,
 10142199: 10142199,
 10142200: 10142200,
 10142201: 10142201,
 10142202: 10142202,
 10142203: 10142203,
 10142204: 10142204,
 10142205: 10142205,
 10142206: 10142206,
 10142207: 10142207,
 10142208: 10142208,
 10142209: 10142209,
 10142210: 10142210,
 10142211: 10142211,
 10142212: 10142212,
 10142213: 10142213,
 10142214: 10142214,
 10142215: 10142215,
 10142216: 10142216,
 10142217: 10142217,
 10142218: 10142218,
 10142219: 10142219,
 10142220: 10142220,
 10142221: 10142221,
 10142222: 10142222,
 10142223: 10142223,
 10142224: 10142224,
 10142225: 10142225,
 10142226: 10142226,
 10142227: 10142227,
 10142228: 10142228,
 10142229: 10142229,
 10142230: 10142230,
 10142231: 10142231,
 10142232: 10142232,
 10142233: 10142233,
 10142234: 10142234,
 10142235: 10142235,
 10142236: 10142236,
 10142237: 10142237,
 10142238: 10142238,
 10142239: 10142239,
 10142240: 10142240,
 10142241: 10142241,
 10142242: 10142242,
 10142243: 10142243,
 10142244: 10142244,
 10142245: 10142245,
 10142246: 10142246,
 10142247: 10142247,
 10142248: 10142248,
 10142249: 10142249,
 10142250: 10142250,
 10142251: 10142251,
 10142252: 10142252,
 10142253: 10142253,
 10142254: 10142254,
 10142255: 10142255,
 10142256: 10142256,
 10142257: 10142257,
 10142258: 10142258,
 10142259: 10142259,
 10142260: 10142260,
 10142261: 10142261,
 10142262: 10142262,
 10142263: 10142263,
 10142264: 10142264,
 10142265: 10142265,
 10142266: 10142266,
 10142267: 10142267,
 10142268: 10142268,
 10142269: 10142269,
 10142270: 10142270,
 10142271: 10142271,
 10142272: 10142272,
 10142273: 10142273,
 10142274: 10142274,
 10142275: 10142275,
 10142276: 10142276,
 10142277: 10142277,
 10142278: 10142278,
 10142279: 10142279,
 10142280: 10142280,
 10142281: 10142281,
 10142282: 10142282,
 10142283: 10142283,
 10142284: 10142284,
 10142285: 10142285,
 10142286: 10142286,
 10142287: 10142287,
 10142288: 10142288,
 10142289: 10142289,
 10142290: 10142290,
 10142291: 10142291,
 10142292: 10142292,
 10142293: 10142293,
 10142294: 10142294,
 10142295: 10142295,
 10142296: 10142296,
 10142297: 10142297,
 10142298: 10142298,
 10142299: 10142299,
 10142300: 10142300,
 10142301: 10142301,
 10142302: 10142302,
 10142303: 10142303,
 10142304: 10142304,
 10142305: 10142305,
 10142306: 10142306,
 10142307: 10142307,
 10142308: 10142308,
 10142309: 10142309,
 10142310: 10142310,
 10142311: 10142311,
 10142312: 10142312,
 10142313: 10142313,
 10142314: 10142314,
 10142315: 10142315,
 10142316: 10142316,
 10142317: 10142317,
 10142318: 10142318,
 10142319: 10142319,
 10142320: 10142320,
 10142321: 10142321,
 10142322: 10142322,
 10142323: 10142323,
 10142324: 10142324,
 10142325: 10142325,
 10142326: 10142326,
 10142327: 10142327,
 10142328: 10142328,
 10142329: 10142329,
 10142330: 10142330,
 10142331: 10142331,
 10142332: 10142332,
 10142333: 10142333,
 10142334: 10142334,
 10142335: 10142335,
 10142336: 10142336,
 10142337: 10142337,
 10142338: 10142338,
 10142339: 10142339,
 10142340: 10142340,
 10142341: 10142341,
 10142342: 10142342,
 10142343: 10142343,
 10142344: 10142344,
 10142345: 10142345,
 10142346: 10142346,
 10142347: 10142347,
 10142348: 10142348,
 10142349: 10142349,
 10142350: 10142350,
 10142351: 10142351,
 10142352: 10142352,
 10142353: 10142353,
 10142354: 10142354,
 10142355: 10142355,
 10142356: 10142356,
 10142357: 10142357,
 10142358: 10142358,
 10142359: 10142359,
 10142360: 10142360,
 10142361: 10142361,
 10142362: 10142362,
 10142363: 10142363,
 10142364: 10142364,
 10142365: 10142365,
 10142366: 10142366,
 10142367: 10142367,
 10142368: 10142368,
 10142369: 10142369,
 10142370: 10142370,
 10142371: 10142371,
 10142372: 10142372,
 10142373: 10142373,
 10142374: 10142374,
 10142375: 10142375,
 10142376: 10142376,
 10142377: 10142377,
 10142378: 10142378,
 10142379: 10142379,
 10142380: 10142380,
 10142381: 10142381,
 10142382: 10142382,
 10142383: 10142383,
 10142384: 10142384,
 10142385: 10142385,
 10142386: 10142386,
 10142387: 10142387,
 10142388: 10142388,
 10142389: 10142389,
 10142390: 10142390,
 10142391: 10142391,
 10142392: 10142392,
 10142393: 10142393,
 10142394: 10142394,
 10142395: 10142395,
 10142396: 10142396,
 10142397: 10142397,
 10142398: 10142398,
 10142399: 10142399,
 10142400: 10142400,
 10142401: 10142401,
 10142402: 10142402,
 10142403: 10142403,
 10142404: 10142404,
 10142405: 10142405,
 10142406: 10142406,
 10142407: 10142407,
 10142408: 10142408,
 10142409: 10142409,
 10142410: 10142410,
 10142411: 10142411,
 10142412: 10142412,
 10142413: 10142413,
 10142414: 10142414,
 10142415: 10142415,
 10142416: 10142416,
 10142417: 10142417,
 10142418: 10142418,
 10142419: 10142419,
 10142420: 10142420,
 10142421: 10142421,
 10142422: 10142422,
 10142423: 10142423,
 10142424: 10142424,
 10142425: 10142425,
 10142426: 10142426,
 10142427: 10142427,
 10142428: 10142428,
 10142429: 10142429,
 10142430: 10142430,
 10142431: 10142431,
 10142432: 10142432,
 10142433: 10142433,
 10142434: 10142434,
 10142435: 10142435,
 10142436: 10142436,
 10142437: 10142437,
 10142438: 10142438,
 10142439: 10142439,
 10142440: 10142440,
 10142441: 10142441,
 10142442: 10142442,
 10142443: 10142443,
 10142444: 10142444,
 10142445: 10142445,
 10142446: 10142446,
 10142447: 10142447,
 10142448: 10142448,
 10142449: 10142449,
 10142450: 10142450,
 10142451: 10142451,
 10142452: 10142452,

# Associação de Códigos no DataFrame Pesquisa
Nesse momento vamos buscar os nomes dos animais e associamos a seu respectivo código.

Em seguida, o mesmo para pessoas, clima, bebida e hobbies.

In [ ]:
df_pesquisa.animal_estimacao = df_animais.animal.map(dict_animais)
df_pesquisa

#df_pesquisa['cod_animal_estimacao']

,cod_pessoa,data_pesquisa,cod_animal_estimacao,cod_clima,cod_bebida,cod_hobbie
0,10142036,2020-01-16,1.0,1.0,1.0,1.0
1,10142053,2020-01-16,2.0,2.0,2.0,2.0
0,10141876,2020-12-19,1.0,1.0,1.0,1.0
1,10141899,2020-12-19,2.0,2.0,2.0,2.0
2,10143110,2020-12-19,3.0,3.0,3.0,3.0
...,...,...,...,...,...,...
1,10141591,2020-07-07,2.0,2.0,2.0,2.0
2,10141873,2020-07-07,3.0,3.0,3.0,3.0
3,10142141,2020-07-07,4.0,NaN,4.0,4.0
4,10142626,2020-07-07,NaN,NaN,5.0,5.0
5,10142979,2020-07-07,NaN,NaN,6.0,6.0

In [ ]:
# Clima
df_pesquisa.clima = df_clima.clima.map(dict_climas)
df_pesquisa

,cod_pessoa,data_pesquisa,cod_animal_estimacao,clima,bebida_favorita,hobbies
0,10142036,2020-01-16,1.0,1.0,Água,Escutar música
1,10142053,2020-01-16,2.0,2.0,refrigerante,Praticar esporte
0,10141876,2020-12-19,1.0,1.0,Vinho,Aprender algo novo
1,10141899,2020-12-19,2.0,2.0,Chá,Pintar quadros
2,10143110,2020-12-19,3.0,3.0,refrigerante,Praticar esporte
...,...,...,...,...,...,...
1,10141591,2020-07-07,2.0,2.0,Cerveja,Ler livros
2,10141873,2020-07-07,3.0,3.0,Café,Aprender algo novo
3,10142141,2020-07-07,4.0,NaN,Chá,Praticar esporte
4,10142626,2020-07-07,NaN,NaN,refrigerante,Ler livros
5,10142979,2020-07-07,NaN,NaN,Café,Dormir

In [ ]:
# Hobbies
df_pesquisa.hobbies = df_hobbie.hobbie.map(dict_hobbies)
df_pesquisa

,cod_pessoa,data_pesquisa,cod_animal_estimacao,clima,bebida_favorita,hobbies
0,10142036,2020-01-16,1.0,1.0,Água,1.0
1,10142053,2020-01-16,2.0,2.0,refrigerante,2.0
0,10141876,2020-12-19,1.0,1.0,Vinho,1.0
1,10141899,2020-12-19,2.0,2.0,Chá,2.0
2,10143110,2020-12-19,3.0,3.0,refrigerante,3.0
...,...,...,...,...,...,...
1,10141591,2020-07-07,2.0,2.0,Cerveja,2.0
2,10141873,2020-07-07,3.0,3.0,Café,3.0
3,10142141,2020-07-07,4.0,NaN,Chá,4.0
4,10142626,2020-07-07,NaN,NaN,refrigerante,5.0
5,10142979,2020-07-07,NaN,NaN,Café,6.0

In [ ]:
# Bebidas
df_pesquisa.bebida_favorita = df_bebida.bebida.map(dict_bebidas)
df_pesquisa

,cod_pessoa,data_pesquisa,cod_animal_estimacao,clima,bebida_favorita,hobbies
0,10142036,2020-01-16,1.0,1.0,1.0,1.0
1,10142053,2020-01-16,2.0,2.0,2.0,2.0
0,10141876,2020-12-19,1.0,1.0,1.0,1.0
1,10141899,2020-12-19,2.0,2.0,2.0,2.0
2,10143110,2020-12-19,3.0,3.0,3.0,3.0
...,...,...,...,...,...,...
1,10141591,2020-07-07,2.0,2.0,2.0,2.0
2,10141873,2020-07-07,3.0,3.0,3.0,3.0
3,10142141,2020-07-07,4.0,NaN,4.0,4.0
4,10142626,2020-07-07,NaN,NaN,5.0,5.0
5,10142979,2020-07-07,NaN,NaN,6.0,6.0

In [ ]:
#df_pesquisa.cod_pessoa = df_pessoas.cod_pessoa.map(dict_pessoas)
#df_pesquisa

## Feito isso, vamos alterar o nome da coluna de todos importados:

1.   Animal Estimação
2.   Pessoa
3.   Clima
4.   Bebida
5.   Hobbies

In [ ]:
# Renomeia as colunas conforme Database
#df_pesquisa = df_pesquisa.rename(columns={'data_coleta' : 'data_pesquisa'})
#df_pesquisa = df_pesquisa.rename(columns={'animal_estimacao' : 'cod_animal_estimacao'})

df_pesquisa = df_pesquisa.rename(columns={'clima' : 'cod_clima'})
df_pesquisa = df_pesquisa.rename(columns={'bebida_favorita' : 'cod_bebida'})
df_pesquisa = df_pesquisa.rename(columns={'hobbies' : 'cod_hobbie'})

# Dropa duas colunas nao mais necessarias
try:
  df_pesquisa.drop('genero', axis=1, inplace=True)
  df_pesquisa.drop('data_nascimento', axis=1, inplace=True)
except Exception as e:
  print(f"Não foi possível dropar colunas. {e}") 

# Exibe o dataframe
df_pesquisa

Não foi possível dropar colunas. O erro foi encontrado foi: "['genero'] not found in axis"

,cod_pessoa,data_pesquisa,cod_animal_estimacao,cod_clima,cod_bebida,cod_hobbie
0,10142036,2020-01-16,1.0,1.0,1.0,1.0
1,10142053,2020-01-16,2.0,2.0,2.0,2.0
0,10141876,2020-12-19,1.0,1.0,1.0,1.0
1,10141899,2020-12-19,2.0,2.0,2.0,2.0
2,10143110,2020-12-19,3.0,3.0,3.0,3.0
...,...,...,...,...,...,...
1,10141591,2020-07-07,2.0,2.0,2.0,2.0
2,10141873,2020-07-07,3.0,3.0,3.0,3.0
3,10142141,2020-07-07,4.0,NaN,4.0,4.0
4,10142626,2020-07-07,NaN,NaN,5.0,5.0
5,10142979,2020-07-07,NaN,NaN,6.0,6.0

# Pronto! Agora é so fazer o insert na tabela do banco.

In [ ]:
for pesquisa in df_pesquisa.itertuples():
    data_pesquisa = str(pesquisa.data_pesquisa)
    cod_pessoa = pesquisa.cod_pessoa
    cod_animal_estimacao = pesquisa.cod_animal_estimacao
    cod_clima = pesquisa.cod_clima
    cod_bebida = pesquisa.cod_bebida
    cod_hobbie = pesquisa.cod_hobbie
    try:        
        query = f"""insert into pesquisa (cod_pessoa, data_pesquisa, 
        cod_animal_estimacao, cod_clima, cod_bebida, cod_hobbie) 
                     values ('{cod_pessoa}','{data_pesquisa}',{cod_animal_estimacao}
                     ,{cod_clima},{cod_bebida},{cod_hobbie})"""
        conn.execute(query)
        print(f"Registro inserido com sucesso: {cod_pessoa}")
    except Exception as e:
        print(f'Não foi possível inserir o registro: {cod_pessoa} Erro: {e}')

## Criando tabela Staging no banco de dados

Uma outra forma de popular dados no banco de dados é através da criação de uma tabela de preparação temporária. Uma tabela Staging é uma area intermediária utilizada para preparar os dados para serem utilizados em um ambiente de análise. 

Deste modo, criamos uma cópia da tabela com os dados coletados e persistimos no banco sem nenhum tratamento.

In [ ]:
# cria uma tabela no banco SQL com o nome 
df_vendas.to_sql('stg_venda_veiculos', con=conn, schema='coletaIGTI')

Após criar a tabela de staging no banco de dados, vamos executar a seguinte consulta em SQL abaixo:

![image.png](attachment:3006f2f5-7863-4398-a336-74c2837947fa.png)

Na tabela principal **stg_venda_veiculos** vamos selecionar os campos: data_compra, valor e cod_pessoa. Além disso, temos que buscar a informação de cod_modelo que esta na tabela **modelo_veiculo**. Para fazer isso vamos realizar uma junção entre as duas tabelas e indicar o campo de descrição como parâmetro. Feito isso, vamos ter os dados necessários para inserir na tabela **venda_veiculo**. 

Pronto! Agora temos todos os dados coletados e armazenados normalizados no banco de dados. \0/